version: "3.9"

services:
  job-application-service:
    build: ./job-application-service
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - job-apply-worker

  job-apply-worker:
    build: ./job-apply-worker-service
    ports:
      - "${WORKER_PORT}:8080"
    environment:
        MONGO_URI: ${MONGO_URI}
